version : '3'
services:
  utsrizki:
    build: ./php
    image: utsrizki_php:latest
    container_name: utsrizki
    hostname: "utsrizki"
    volumes:
      - ./src-utswahyu:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - bd_uts
  bd_uts:
    image: mariadb:10.2
    container_name: bd_uts
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: markocoy
      MYSQL_PASSWORD: markocoy1!.
      MYSQL_ROOT_PASSWORD: markocoy1
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_pemweb:
    build: ./nginx
    image: nginx_pemweb:latest
    container_name: nginx_pemweb
    hostname: "nginx_pemweb"
    ports:
      - "80:80"
    volumes:
      - ./src-utswahyu:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - utsrizki